version: '3.7'
services:
  kong:
    image: kong:latest
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stderr
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:9090
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - '9090:9090'
      - '8443:8443'
      - '8002:8002'
      - '127.0.0.1:8001:8001'
      - '127.0.0.1:8444:8444'
    networks:
      - kong-net
networks:
  kong-net:
    driver: bridge
